spring.application.name=EduPulseBackend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.data.mongodb.uri=mongodb+srv://gunathilakaranketh:sasiru123@edupulse.oovinf0.mongodb.net/EduPulse?retryWrites=true&w=majority&appName=EduPulse