spring.application.name=EduPulseBackend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.data.mongodb.uri=mongodb+srv://dasunhimsara:dasun123@edupulse.oovinf0.mongodb.net/EduPulse?retryWrites=true&w=majority&appName=EduPulse
#spring.data.mongodb.uri=mongodb+srv://gunathilakaranketh:sasiru123@edupulse.oovinf0.mongodb.net/EduPulse?retryWrites=true&w=majority&appName=EduPulse

file.storage.base=uploads/
file.storage.image-folder=images/
file.storage.video-folder=videos/


# Google OAuth2 config
spring.security.oauth2.client.registration.google.client-id=682477946273-rb38mvvqp5c2peeu8n0ngq7i88l1gg12.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uris=http://localhost:8080/
spring.security.oauth2.client.registration.google.scope=profile,email

upload.directory=/Users/donmariopriyankasubasinghe/Desktop/
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB