spring.application.name=EduPulseBackend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
#spring.data.mongodb.uri=mongodb+srv://gunathilakaranketh:sasiru123@edupulse.oovinf0.mongodb.net/EduPulse?retryWrites=true&w=majority&appName=EduPulse

file.storage.base=uploads/
file.storage.image-folder=images/
file.storage.video-folder=videos/

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB